version: "3"
services:
  fastapi:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:14.5-bullseye
    restart: always
    environment:
      POSTGRES_DB: FavorsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kazuki123
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
networks:
  app-network:
    driver: bridge


  # service_pgadmin:
  #   image: dpage/pgadmin4:6.11
  #   container_name: container_pgadmin
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - volume_pgadmin:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: kazukikagoshima2@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: Kazuki123

volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga
