version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: FavorsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kazuki123
    volumes:
      # - ./backend/database/data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports: 
      - "5432:5432"

volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga
